const PRICE_CONFIG = {
  URL: "https://www.goal.com/th/ไลฟ์สกอร์",
    SELECTOR: {
        DATE: "",
        UPDATE_TIME: "body.layout-master.layout-main-with-sidebar.page-live-scores > div.page-container > div.page-container-bg > div.mr-gutters.main-container.clearfix > div.main-content > div.widget-fixtures-and-results > div.competition-matches > a.competition-title > div.competition-name",

        date1: "body.layout-master.layout-main-with-sidebar.page-live-scores > div.page-container > div.page-container-bg > div.mr-gutters.main-container.clearfix > div.main-content > div.widget-fixtures-and-results > div.competition-matches:nth-child(5) > div.match-row-list > div.match-row.status-fix:nth-child(1) > div.match-main-data > a.match-main-data-link > div.match-status > time",
        date2: "body.layout-master.layout-main-with-sidebar.page-live-scores > div.page-container > div.page-container-bg > div.mr-gutters.main-container.clearfix > div.main-content > div.widget-fixtures-and-results > div.competition-matches:nth-child(6) > div.match-row-list > div.match-row.status-fix:nth-child(1) > div.match-main-data > a.match-main-data-link > div.match-status > time",
        date3: "body.layout-master.layout-main-with-sidebar.page-live-scores > div.page-container > div.page-container-bg > div.mr-gutters.main-container.clearfix > div.main-content > div.widget-fixtures-and-results > div.competition-matches:nth-child(8) > div.match-row-list > div.match-row.status-fix:nth-child(1) > div.match-main-data > a.match-main-data-link > div.match-status > time",
        date4: "body.layout-master.layout-main-with-sidebar.page-live-scores > div.page-container > div.page-container-bg > div.mr-gutters.main-container.clearfix > div.main-content > div.widget-fixtures-and-results > div.competition-matches:nth-child(9) > div.match-row-list > div.match-row.status-fix:nth-child(1) > div.match-main-data > a.match-main-data-link > div.match-status > time",
        date5: "body.layout-master.layout-main-with-sidebar.page-live-scores > div.page-container > div.page-container-bg > div.mr-gutters.main-container.clearfix > div.main-content > div.widget-fixtures-and-results > div.competition-matches:nth-child(12) > div.match-row-list > div.match-row.status-fix:nth-child(1) > div.match-main-data > a.match-main-data-link > div.match-status > time",


        then1: "body.layout-master.layout-main-with-sidebar.page-live-scores > div.page-container > div.page-container-bg > div.mr-gutters.main-container.clearfix > div.main-content > div.widget-fixtures-and-results > div.competition-matches:nth-child(5) > div.match-row-list > div.match-row.status-fix:nth-child(1) > div.match-main-data > a.match-main-data-link > div.match-teams > div.match-data:nth-child(1) > div.team-home > span.team-name",
        then2: "body.layout-master.layout-main-with-sidebar.page-live-scores > div.page-container > div.page-container-bg > div.mr-gutters.main-container.clearfix > div.main-content > div.widget-fixtures-and-results > div.competition-matches:nth-child(5) > div.match-row-list > div.match-row.status-fix:nth-child(1) > div.match-main-data > a.match-main-data-link > div.match-teams > div.match-data:nth-child(1) > div.team-away > span.team-name",
        then3: "body.layout-master.layout-main-with-sidebar.page-live-scores > div.page-container > div.page-container-bg > div.mr-gutters.main-container.clearfix > div.main-content > div.widget-fixtures-and-results > div.competition-matches:nth-child(6) > div.match-row-list > div.match-row.status-fix:nth-child(1) > div.match-main-data > a.match-main-data-link > div.match-teams > div.match-data:nth-child(1) > div.team-home > span.team-name",
        then4: "body.layout-master.layout-main-with-sidebar.page-live-scores > div.page-container > div.page-container-bg > div.mr-gutters.main-container.clearfix > div.main-content > div.widget-fixtures-and-results > div.competition-matches:nth-child(6) > div.match-row-list > div.match-row.status-fix:nth-child(1) > div.match-main-data > a.match-main-data-link > div.match-teams > div.match-data:nth-child(1) > div.team-away  > span.team-name",
        then5: "body.layout-master.layout-main-with-sidebar.page-live-scores > div.page-container > div.page-container-bg > div.mr-gutters.main-container.clearfix > div.main-content > div.widget-fixtures-and-results > div.competition-matches:nth-child(8) > div.match-row-list > div.match-row.status-fix:nth-child(1) > div.match-main-data > a.match-main-data-link > div.match-teams > div.match-data:nth-child(1) > div.team-home > span.team-name",
        then6: "body.layout-master.layout-main-with-sidebar.page-live-scores > div.page-container > div.page-container-bg > div.mr-gutters.main-container.clearfix > div.main-content > div.widget-fixtures-and-results > div.competition-matches:nth-child(8) > div.match-row-list > div.match-row.status-fix:nth-child(1) > div.match-main-data > a.match-main-data-link > div.match-teams > div.match-data:nth-child(1) > div.team-away > span.team-name",
        then7: "body.layout-master.layout-main-with-sidebar.page-live-scores > div.page-container > div.page-container-bg > div.mr-gutters.main-container.clearfix > div.main-content > div.widget-fixtures-and-results > div.competition-matches:nth-child(9) > div.match-row-list > div.match-row.status-fix:nth-child(1) > div.match-main-data > a.match-main-data-link > div.match-teams > div.match-data:nth-child(1) > div.team-home > span.team-name",
        then8: "body.layout-master.layout-main-with-sidebar.page-live-scores > div.page-container > div.page-container-bg > div.mr-gutters.main-container.clearfix > div.main-content > div.widget-fixtures-and-results > div.competition-matches:nth-child(9) > div.match-row-list > div.match-row.status-fix:nth-child(1) > div.match-main-data > a.match-main-data-link > div.match-teams > div.match-data:nth-child(1) > div.team-away > span.team-name",
        then9: "body.layout-master.layout-main-with-sidebar.page-live-scores > div.page-container > div.page-container-bg > div.mr-gutters.main-container.clearfix > div.main-content > div.widget-fixtures-and-results > div.competition-matches:nth-child(12) > div.match-row-list > div.match-row.status-fix:nth-child(1) > div.match-main-data > a.match-main-data-link > div.match-teams > div.match-data:nth-child(1) > div.team-home > span.team-name",
        then10: "body.layout-master.layout-main-with-sidebar.page-live-scores > div.page-container > div.page-container-bg > div.mr-gutters.main-container.clearfix > div.main-content > div.widget-fixtures-and-results > div.competition-matches:nth-child(12) > div.match-row-list > div.match-row.status-fix:nth-child(1) > div.match-main-data > a.match-main-data-link > div.match-teams > div.match-data:nth-child(1) > div.team-away > span.team-name",
        then11: "body.layout-master.layout-main-with-sidebar.page-live-scores > div.page-container > div.page-container-bg > div.mr-gutters.main-container.clearfix > div.main-content > div.widget-fixtures-and-results > div.competition-matches:nth-child(20) > div.match-row-list > div.match-row.status-fix:nth-child(1) > div.match-main-data > a.match-main-data-link > div.match-teams > div.match-data > div.team-home > span.team-name",
        then12: "body.layout-master.layout-main-with-sidebar.page-live-scores > div.page-container > div.page-container-bg > div.mr-gutters.main-container.clearfix > div.main-content > div.widget-fixtures-and-results > div.competition-matches:nth-child(20) > div.match-row-list > div.match-row.status-fix:nth-child(1) > div.match-main-data > a.match-main-data-link > div.match-teams > div.match-data > div.team-away > span.team-name",

        leag: "body.layout-master.layout-main-with-sidebar.page-live-scores > div.page-container > div.page-container-bg > div.mr-gutters.main-container.clearfix > div.main-content > div.widget-fixtures-and-results > div.competition-matches:nth-child(5) > a.competition-title > div.competition-name",
        leag1: "body.layout-master.layout-main-with-sidebar.page-live-scores > div.page-container > div.page-container-bg > div.mr-gutters.main-container.clearfix > div.main-content > div.widget-fixtures-and-results > div.competition-matches:nth-child(6) > a.competition-title > div.competition-name",
        leag2: "body.layout-master.layout-main-with-sidebar.page-live-scores > div.page-container > div.page-container-bg > div.mr-gutters.main-container.clearfix > div.main-content > div.widget-fixtures-and-results > div.competition-matches:nth-child(8) > a.competition-title > div.competition-name",
        leag3: "body.layout-master.layout-main-with-sidebar.page-live-scores > div.page-container > div.page-container-bg > div.mr-gutters.main-container.clearfix > div.main-content > div.widget-fixtures-and-results > div.competition-matches:nth-child(9) > a.competition-title > div.competition-name",
        leag4: "body.layout-master.layout-main-with-sidebar.page-live-scores > div.page-container > div.page-container-bg > div.mr-gutters.main-container.clearfix > div.main-content > div.widget-fixtures-and-results > div.competition-matches:nth-child(12) > a.competition-title > div.competition-name",
        leag5: "body.layout-master.layout-main-with-sidebar.page-live-scores > div.page-container > div.page-container-bg > div.mr-gutters.main-container.clearfix > div.main-content > div.widget-fixtures-and-results > div.competition-matches:nth-child(20) > a.competition-title > div.competition-name",
        leag6: "",
        leag7: "",
        leag8: "",
        leag9: "",

        sco: "body.layout-master.layout-main-with-sidebar.page-live-scores > div.page-container > div.page-container-bg > div.mr-gutters.main-container.clearfix > div.main-content > div.widget-fixtures-and-results > div.competition-matches:nth-child(5) > div.match-row-list > div.match-row.status-fix:nth-child(1) > div.match-main-data > a.match-main-data-link > div.match-teams > div.match-data:nth-child(1) > div.line",
        sco1: "body.layout-master.layout-main-with-sidebar.page-live-scores > div.page-container > div.page-container-bg > div.mr-gutters.main-container.clearfix > div.main-content > div.widget-fixtures-and-results > div.competition-matches:nth-child(6) > div.match-row-list > div.match-row.status-fix:nth-child(1) > div.match-main-data > a.match-main-data-link > div.match-teams > div.match-data:nth-child(1) > div.line",
        sco2: "body.layout-master.layout-main-with-sidebar.page-live-scores > div.page-container > div.page-container-bg > div.mr-gutters.main-container.clearfix > div.main-content > div.widget-fixtures-and-results > div.competition-matches:nth-child(8) > div.match-row-list > div.match-row.status-fix:nth-child(1) > div.match-main-data > a.match-main-data-link > div.match-teams > div.match-data:nth-child(1) > div.line",
        sco3: "body.layout-master.layout-main-with-sidebar.page-live-scores > div.page-container > div.page-container-bg > div.mr-gutters.main-container.clearfix > div.main-content > div.widget-fixtures-and-results > div.competition-matches:nth-child(9) > div.match-row-list > div.match-row.status-fix:nth-child(1) > div.match-main-data > a.match-main-data-link > div.match-teams > div.match-data:nth-child(1) > div.line",
        sco4: "body.layout-master.layout-main-with-sidebar.page-live-scores > div.page-container > div.page-container-bg > div.mr-gutters.main-container.clearfix > div.main-content > div.widget-fixtures-and-results > div.competition-matches:nth-child(12) > div.match-row-list > div.match-row.status-fix:nth-child(1) > div.match-main-data > a.match-main-data-link > div.match-teams > div.match-data:nth-child(1) > div.line",
        
        pricename1: "body > div.container > div.row > div.col-sm-8 > span#pro1-147 > div.row > div.col-12.text-center > h4 > a",
        pricename2: "body > div.container > div.row > div.col-sm-8 > span#pro1-145 > div.row > div.col-12.text-center > h4 > a",
         
    },
};

export default PRICE_CONFIG;
